export const RoutePaths = {
  DEFAULT: '',
  HOME: 'home',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASS: 'reset-pass',
  RESEND_EMAIL: 'resend-email',
  REGISTER_SUCCESS: 'register-success',
  VALIDATE_EMAIL: 'validate-email',
  MAP: 'map',
  SEARCH: 'search',
  PROFILE: 'profile',
  ABOUT: 'about',
  CONTACT: 'contact',
  HUNT: 'hunt',
  HUNT_DETAILS: 'hunt/details',
  HUNT_CREATE: 'hunt/create',
  HUNT_UPDATE: 'hunt/update',
  LINK_MAP: 'hunt/create/add-map',
  HUNT_SUCCESS: 'hunt/create/success',
  HUNT_INVITES: 'hunt/invites',
  HUNT_PARTICIPATING: 'hunt/participating',
};
