export const RoutePaths = {
  DEFAULT: '',
  HOME: 'home',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASS: 'reset-pass',
  RESEND_EMAIL: 'resend-email',
  REGISTER_SUCCESS: 'register-success',
  VALIDATE_EMAIL: 'validate-email',
  PROFILE: 'profile',
  ABOUT: 'about',
  CONTACT: 'contact',
  HUNT: 'hunt',
  HUNT_CREATE: 'hunt/create',
};
